let state; const $=s=>document.querySelector(s);
async function load(){state=await (await fetch('/state')).json();render();}
function save(){fetch('/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});render();}
function n(side,key,d){const limits={gen:5,hook:12,first:4};state[side][key]=Math.min(limits[key],Math.max(0,state[side][key]+d));save()}
function score(side,d){let k='score'+side;state[k]=Math.max(0,state[k]+d);save()}
function resetPos(group){const m={nameA:['nameAX','nameAY'],roleA:['roleAX','roleAY'],statsA:['statsAX','statsAY'],nameB:['nameBX','nameBY'],roleB:['roleBX','roleBY'],statsB:['statsBX','statsBY']};for(const k of m[group]||[])state[k]=0;save()}
function applyPreset(v){const p={classic:{accentColor:'#ffffff',teamAColor:'#ffffff',teamBColor:'#ffffff',nameColor:'#ffffff',numberColor:'#ffffff',bgOpacity:88},icefire:{accentColor:'#ffffff',teamAColor:'#39a8ff',teamBColor:'#ff4d3d',nameColor:'#ffffff',numberColor:'#ffffff',bgOpacity:82},neon:{accentColor:'#b8ff2c',teamAColor:'#20e3ff',teamBColor:'#ff38d1',nameColor:'#ffffff',numberColor:'#ffffff',bgOpacity:72},mono:{accentColor:'#bfc5cc',teamAColor:'#e8e8e8',teamBColor:'#8f969e',nameColor:'#ffffff',numberColor:'#ffffff',bgOpacity:70},gold:{accentColor:'#e6b84a',teamAColor:'#f6d879',teamBColor:'#d78b38',nameColor:'#fff4d0',numberColor:'#ffffff',bgOpacity:86}};if(p[v])Object.assign(state,p[v]);save()}
function resetAppearance(){Object.assign(state,{accentColor:'#ffffff',teamAColor:'#ffffff',teamBColor:'#ffffff',nameColor:'#ffffff',numberColor:'#ffffff',textFont:'Arial',numberFont:'Arial',bgOpacity:88,showBorder:true,textOutline:true,hudScale:100,teamNameScale:100,statsScale:100,champScale:100,roleIconScale:100,hudY:78,outlineSize:2,shadowSize:4});save()}
function defaults(){const d={championship:'DBD CHAMPIONSHIP',teamA:'TIME A',teamB:'TIME B',overlayStyle:1,accentColor:'#ffffff',teamAColor:'#ffffff',teamBColor:'#ffffff',nameColor:'#ffffff',numberColor:'#ffffff',textFont:'Arial',numberFont:'Arial',bgOpacity:88,showBorder:true,textOutline:true,showRoles:true,showRoleLabels:true,killerSide:'A',showSet:true,hudScale:100,teamNameScale:100,statsScale:100,champScale:100,roleIconScale:100,hudY:78,outlineSize:2,shadowSize:4,nameAX:0,nameAY:0,nameBX:0,nameBY:0,roleAX:0,roleAY:0,roleBX:0,roleBY:0,statsAX:0,statsAY:0,statsBX:0,statsBY:0};for(const [k,v] of Object.entries(d))if(state[k]===undefined)state[k]=v;}
function render(){defaults();$('#championship').value=state.championship;$('#overlayStyle').value=state.overlayStyle;for(const k of ['accentColor','teamAColor','teamBColor','nameColor','numberColor'])if($('#'+k))$('#'+k).value=state[k];const tf=$('#textFont'),nf=$('#numberFont');if(tf)tf.value=state.textFont;if(nf)nf.value=state.numberFont;for(const [id,key,suffix] of [['bgOpacity','bgOpacity','%'],['hudScale','hudScale','%'],['teamNameScale','teamNameScale','%'],['statsScale','statsScale','%'],['champScale','champScale','%'],['roleIconScale','roleIconScale','%'],['hudY','hudY',' px'],['outlineSize','outlineSize',' px'],['shadowSize','shadowSize',' px']]){const e=$('#'+id);if(e){e.value=state[key];$('#'+id+'Value').textContent=state[key]+suffix;}}$('#showBorder').checked=state.showBorder;$('#textOutline').checked=state.textOutline;$('#showRoles').checked=state.showRoles;$('#showRoleLabels').checked=state.showRoleLabels;$('#showSet').checked=state.showSet;const kr=document.querySelector('input[name="killerSide"][value="'+state.killerSide+'"]');if(kr)kr.checked=true;$('#teamA').value=state.teamA;$('#teamB').value=state.teamB;$('#scoreA').textContent=state.scoreA;$('#scoreB').textContent=state.scoreB;for(const s of ['a','b'])for(const k of ['gen','hook','first'])$('#'+s+k).textContent=state[s][k];$('#currentSet').value=Math.max(1,Math.min(9,+state.currentSet||1));for(const key of ['nameAX','nameAY','roleAX','roleAY','statsAX','statsAY','nameBX','nameBY','roleBX','roleBY','statsBX','statsBY']){const e=$('#'+key);if(e){e.value=state[key]||0;const v=$('#'+key+'Value');if(v)v.textContent=(state[key]||0)+' px';}}}
window.onload=load;
