let state; const $=s=>document.querySelector(s); let pendingColor=null; let editingPresetName='';
const presetKeys=['accentColor','numberColor','teamAColor','teamBColor','bgOpacity','hudScale','teamNameScale','statsScale','champScale','roleIconScale','roleLabelScale','setScale'];
async function load(){state=await (await fetch('/state')).json();render();}
function save(){fetch('/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});render();}
function n(side,key,d){const limits={gen:5,hook:12,first:4};state[side][key]=Math.min(limits[key],Math.max(0,state[side][key]+d));save()}
function score(side,d){let k='score'+side;state[k]=Math.max(0,state[k]+d);save()}
function resetPos(group){const m={nameA:['nameAX','nameAY'],roleA:['roleAX','roleAY'],statsA:['statsAX','statsAY'],nameB:['nameBX','nameBY'],roleB:['roleBX','roleBY'],statsB:['statsBX','statsBY']};for(const k of m[group]||[])state[k]=0;save()}
function markCustom(){if(!editingPresetName){const s=$('#appearancePreset');if(s)s.value='';}}
function requestColorConfirm(key,value){pendingColor={key,value,old:state[key]};$('#colorPreview').style.background=value;$('#colorConfirmModal').hidden=false;}
function confirmColor(){if(!pendingColor)return;state[pendingColor.key]=pendingColor.value;pendingColor=null;$('#colorConfirmModal').hidden=true;markCustom();save();}
function cancelColor(){if(!pendingColor)return;const el=$('#'+pendingColor.key);if(el)el.value=pendingColor.old;pendingColor=null;$('#colorConfirmModal').hidden=true;}
function presetChanged(v){if(v==='__new__'){createPreset();return} if(!v){editingPresetName='';$('#savePresetBtn').hidden=true;return}const p=(state.customPresets||[]).find(x=>x.name===v);if(p){Object.assign(state,p.values);editingPresetName=p.name;$('#savePresetBtn').hidden=false;save();}}
function createPreset(){state.customPresets ||= [];if(state.customPresets.length>=5){alert('Limite de 5 presets atingido.');renderPresetSelect();return;}let name=prompt('Nome do novo preset:','');if(name===null){renderPresetSelect();return;}name=name.trim().slice(0,28);if(!name){alert('Digite um nome para o preset.');renderPresetSelect();return;}if(state.customPresets.some(p=>p.name.toLowerCase()===name.toLowerCase())){alert('Já existe um preset com esse nome.');renderPresetSelect();return;}editingPresetName=name;renderPresetSelect();$('#appearancePreset').value='__draft__';$('#savePresetBtn').hidden=false;}
function saveCurrentPreset(){if(!editingPresetName)return;state.customPresets ||= [];const values={};for(const k of presetKeys)values[k]=state[k];const i=state.customPresets.findIndex(p=>p.name===editingPresetName);const item={name:editingPresetName,values};if(i>=0)state.customPresets[i]=item;else if(state.customPresets.length<5)state.customPresets.push(item);editingPresetName='';save();setTimeout(()=>{$('#appearancePreset').value=item.name},0);}
function renderPresetSelect(){const el=$('#appearancePreset');if(!el)return;const selected=editingPresetName||el.value||'';el.innerHTML='<option value="">Personalizado</option>'+(state.customPresets||[]).map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('')+(editingPresetName&&!state.customPresets.some(p=>p.name===editingPresetName)?`<option value="__draft__">${esc(editingPresetName)} (novo)</option>`:'')+'<option value="__new__">＋ Criar preset</option>';if(editingPresetName)el.value=state.customPresets.some(p=>p.name===editingPresetName)?editingPresetName:'__draft__';else if([...el.options].some(o=>o.value===selected))el.value=selected;}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function resetAppearance(){Object.assign(state,{accentColor:'#ffffff',teamAColor:'#ffffff',teamBColor:'#ffffff',numberColor:'#ffffff',textFont:'Arial',numberFont:'Arial',bgOpacity:88,showBorder:true,textOutline:true,hudScale:100,teamNameScale:100,statsScale:100,champScale:100,roleIconScale:100,roleLabelScale:100,setScale:100,hudY:78,outlineSize:2,shadowSize:4});editingPresetName='';save()}
function defaults(){const d={championship:'DBD CHAMPIONSHIP',teamA:'TIME A',teamB:'TIME B',overlayStyle:1,accentColor:'#ffffff',teamAColor:'#ffffff',teamBColor:'#ffffff',numberColor:'#ffffff',textFont:'Arial',numberFont:'Arial',bgOpacity:88,showBorder:true,textOutline:true,showRoles:true,showRoleLabels:true,killerSide:'A',showSet:true,hudScale:100,teamNameScale:100,statsScale:100,champScale:100,roleIconScale:100,roleLabelScale:100,setScale:100,hudY:78,outlineSize:2,shadowSize:4,customPresets:[],nameAX:0,nameAY:0,nameBX:0,nameBY:0,roleAX:0,roleAY:0,roleBX:0,roleBY:0,statsAX:0,statsAY:0,statsBX:0,statsBY:0};for(const [k,v] of Object.entries(d))if(state[k]===undefined)state[k]=v;}
function render(){defaults();$('#championship').value=state.championship;$('#overlayStyle').value=state.overlayStyle;for(const k of ['accentColor','teamAColor','teamBColor','numberColor'])if($('#'+k))$('#'+k).value=state[k];const tf=$('#textFont'),nf=$('#numberFont');if(tf)tf.value=state.textFont;if(nf)nf.value=state.numberFont;for(const [id,key,suffix] of [['bgOpacity','bgOpacity','%'],['hudScale','hudScale','%'],['teamNameScale','teamNameScale','%'],['statsScale','statsScale','%'],['champScale','champScale','%'],['roleIconScale','roleIconScale','%'],['roleLabelScale','roleLabelScale','%'],['setScale','setScale','%'],['hudY','hudY',' px'],['outlineSize','outlineSize',' px'],['shadowSize','shadowSize',' px']]){const e=$('#'+id);if(e){e.value=state[key];$('#'+id+'Value').textContent=state[key]+suffix;}}$('#showBorder').checked=state.showBorder;$('#textOutline').checked=state.textOutline;$('#showRoles').checked=state.showRoles;$('#showRoleLabels').checked=state.showRoleLabels;$('#showSet').checked=state.showSet;const kr=document.querySelector('input[name="killerSide"][value="'+state.killerSide+'"]');if(kr)kr.checked=true;$('#teamA').value=state.teamA;$('#teamB').value=state.teamB;$('#scoreA').textContent=state.scoreA;$('#scoreB').textContent=state.scoreB;for(const s of ['a','b'])for(const k of ['gen','hook','first'])$('#'+s+k).textContent=state[s][k];$('#currentSet').value=Math.max(1,Math.min(9,+state.currentSet||1));for(const key of ['nameAX','nameAY','roleAX','roleAY','statsAX','statsAY','nameBX','nameBY','roleBX','roleBY','statsBX','statsBY']){const e=$('#'+key);if(e){e.value=state[key]||0;const v=$('#'+key+'Value');if(v)v.textContent=(state[key]||0)+' px';}}renderPresetSelect();$('#savePresetBtn').hidden=!editingPresetName;}
window.onload=load;
