const http=require('http'),fs=require('fs'),path=require('path');
const root=__dirname, clients=new Set();
let state={overlayStyle:1,accentColor:'#ffffff',numberColor:'#ffffff',teamAColor:'#ffffff',teamBColor:'#ffffff',textFont:'Arial',numberFont:'Arial',teamNameScale:100,statsScale:100,champScale:100,roleIconScale:100,roleLabelScale:100,setScale:100,customPresets:[],bgOpacity:88,showBorder:true,textOutline:true,showRoles:true,showRoleLabels:true,killerSide:'A',showSet:true,championship:'DBD CHAMPIONSHIP',teamA:'TIME A',teamB:'TIME B',scoreA:0,scoreB:0,currentSet:1,a:{gen:0,hook:0,first:0},b:{gen:0,hook:0,first:0}};
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'};
const server=http.createServer((req,res)=>{
 if(req.url==='/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(`data: ${JSON.stringify(state)}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res));return;}
 if(req.url==='/state'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify(state));}
 if(req.url==='/state'&&req.method==='POST'){let body='';req.on('data',d=>body+=d);req.on('end',()=>{try{state=JSON.parse(body);state.championship=state.championship||'DBD CHAMPIONSHIP';state.overlayStyle=Math.max(1,Math.min(30,+state.overlayStyle||1));state.accentColor=/^#[0-9a-f]{6}$/i.test(state.accentColor||'')?state.accentColor:'#ffffff';state.numberColor=/^#[0-9a-f]{6}$/i.test(state.numberColor||'')?state.numberColor:'#ffffff';state.teamAColor=/^#[0-9a-f]{6}$/i.test(state.teamAColor||'')?state.teamAColor:'#ffffff';state.teamBColor=/^#[0-9a-f]{6}$/i.test(state.teamBColor||'')?state.teamBColor:'#ffffff';state.textOutline=state.textOutline!==false;state.showRoles=state.showRoles!==false;state.showRoleLabels=state.showRoleLabels!==false;state.showSet=state.showSet!==false;state.currentSet=Math.max(1,Math.min(9,+state.currentSet||1));state.killerSide=state.killerSide==='B'?'B':'A';state.bgOpacity=Math.max(0,Math.min(100,+state.bgOpacity||0));state.showBorder=state.showBorder!==false;state.hudScale=Math.max(70,Math.min(140,+state.hudScale||100));state.hudY=Math.max(20,Math.min(260,+state.hudY||78));state.outlineSize=Math.max(0,Math.min(5,+state.outlineSize||0));state.shadowSize=Math.max(0,Math.min(12,+state.shadowSize||0));for(const k of ['teamNameScale','statsScale','champScale','roleIconScale','roleLabelScale','setScale'])state[k]=Math.max(60,Math.min(180,+state[k]||100));state.customPresets=Array.isArray(state.customPresets)?state.customPresets.slice(0,5):[];for(const k of ['nameAX','nameAY','nameBX','nameBY','roleAX','roleAY','roleBX','roleBY','statsAX','statsAY','statsBX','statsBY'])state[k]=Math.max(-220,Math.min(220,+state[k]||0));for(const side of ['a','b']){state[side].gen=Math.max(0,Math.min(5,+state[side].gen||0));state[side].hook=Math.max(0,Math.min(12,+state[side].hook||0));state[side].first=Math.max(0,Math.min(4,+state[side].first||0));}for(const c of clients)c.write(`data: ${JSON.stringify(state)}\n\n`);res.writeHead(204);res.end();}catch(e){res.writeHead(400);res.end('bad json')}});return;}
 let p=req.url==='/'?'/panel.html':decodeURIComponent(req.url.split('?')[0]);p=path.join(root,p);if(!p.startsWith(root)){res.writeHead(403);return res.end();}fs.readFile(p,(e,d)=>{if(e){res.writeHead(404);res.end('Not found');}else{res.writeHead(200,{'Content-Type':mime[path.extname(p)]||'application/octet-stream'});res.end(d);}})
});
server.listen(8765,'127.0.0.1',()=>console.log('DBD Overlay: http://127.0.0.1:8765/panel.html'));
